### ISSUE TITLE
Error when editing posts

### ISSUE THREAD

**Issue by sandratatarevicova** [julianlam/nodebb-plugin-knowledge-base#6]
The following error sometimes occurs when editing posts:

```
2020-12-07T14:20:02.071Z [4568/252] - error: posts.loadPostTools
TypeError: Cannot read property 'posts' of undefined
    at Object.plugin.allowEditing [as method] (/usr/src/app/node_modules/nodebb-plugin-knowledge-base/library.js:56:37)
    at /usr/src/app/src/plugins/hooks.js:128:28
    at /usr/src/app/node_modules/async/dist/async.js:1631:13
    at replenish (/usr/src/app/node_modules/async/dist/async.js:440:21)
    at /usr/src/app/node_modules/async/dist/async.js:445:13
    at eachOfLimit$1 (/usr/src/app/node_modules/async/dist/async.js:471:34)
    at awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)
    at eachOfSeries (/usr/src/app/node_modules/async/dist/async.js:658:16)
    at awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)
    at Object.reduce (/usr/src/app/node_modules/async/dist/async.js:1630:16)
```

We are currently running NodeBB v1.15.3.

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-knowledge-base/commit/f7bdd016c2776e68599447ebd3e14b2fcc9183b8, @julianlam can you publish new version with ^1.15.0 compatibility

**Comment by julianlam** [comment]
Added you to maintainers, can you publish?

**Comment by barisusakli** [comment]
Done, @sandratatarevicova 1.1.0 should fix this issue.
